version: '3.8'

services:
  app-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: churn-prediction-app-api
    command: api
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    environment:
      - FLASK_APP=main_api.py
      - FLASK_ENV=development
    networks:
      - elastic-kibana_elastic
      - app-network

  app-db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: churn-prediction-app-db
    command: db
    ports:
      - "8001:8000"
    volumes:
      - ./logs:/app/logs
    environment:
      - FLASK_APP=main_db.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/mlops_db
      - DATABASE_HOST=host.docker.internal
    networks:
      - elastic-kibana_elastic
      - app-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.1
    container_name: filebeat
    user: root
    volumes:
      - ./logs:/app/logs:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - elastic-kibana_elastic
    depends_on:
      - app-api
      - app-db

networks:
  elastic-kibana_elastic:
    external: true
  app-network:
    driver: bridge
